version: '3.7'
x-node:
  &default-node
  build: ./node
  env_file: ./secret/node.env
  privileged: true
  networks:
    - tiops
  ports:
    - ${TIOPS_PORT:-22}

services:
  control:
    container_name: tiops-control
    hostname: control
    build: ./control
    env_file: ./secret/control.env
    privileged: true
    ports:
      - "8080"
    networks:
       tiops:
         ipv4_address: 172.19.0.100
  n1:
    << : *default-node
    container_name: tiops-n1
    hostname: n1
    networks:
         tiops:
           ipv4_address: 172.19.0.101

# docker network create --gateway 172.19.0.1 --subnet 172.19.0.0/16 tiops
networks:
  tiops:
    external: true
    ipam:
      config:
        - subnet: 172.19.0.0/16
